import { Activity, ArrowRight, CalendarDays, Check, Clock3, FolderKanban, ListTodo, Plus, Settings2, ShieldCheck, Users } from "lucide-react";
import type { WorkspaceProject, WorkspaceTask } from "./types";

type WorkUpdate = { task: string; taskId: string; progress: number; note: string; when: string; evidence?: string };
type Props = {
  userName: string;
  organizationName: string;
  tasks: WorkspaceTask[];
  projects: WorkspaceProject[];
  teamCount: number;
  workUpdates: WorkUpdate[];
  onCreateTask: () => void;
  onOpenScreen: (screen: string) => void;
  onChangeStatus: (task: WorkspaceTask, status: string) => void;
};

// OVERVIEW SCREEN: give a teammate a quick, honest summary of today's work and project progress.
export function OverviewScreen({ userName, organizationName, tasks, projects, teamCount, workUpdates, onCreateTask, onOpenScreen, onChangeStatus }: Props) {
  const dueTodayCount = tasks.filter((task) => task.date === new Date().toLocaleDateString()).length;
  const completedCount = tasks.filter((task) => task.state === "Completed").length;
  const reviewCount = tasks.filter((task) => task.state === "In review").length;
  const completedPercent = tasks.length ? Math.round(completedCount / tasks.length * 100) : 0;
  const firstName = userName.split(" ")[0] || "there";
  const dayPart = new Date().getHours() < 12 ? "morning" : new Date().getHours() < 18 ? "afternoon" : "evening";
  return <>
    <div className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> {new Date().toLocaleDateString(undefined, { weekday: "long", month: "long", day: "numeric", year: "numeric" }).toUpperCase()}</div><h1>Good {dayPart}, {firstName} <span className="wave">✳</span></h1><p className="welcome-sub">Here’s what’s happening across {organizationName} today.</p></div><button className="primary-button" onClick={onCreateTask}><Plus size={17}/> Create task</button></div>
    <div className="metric-grid">
      <article className="metric-card"><div className="metric-top"><span>Tasks</span><span className="metric-icon violet"><ListTodo size={16}/></span></div><div className="metric-value">{tasks.length.toString().padStart(2, "0")} <small>tasks</small></div><div className="metric-bottom"><span>{tasks.filter((task) => task.state !== "Completed").length} still open</span><button className="metric-link" onClick={() => onOpenScreen("My work")}>View tasks <ArrowRight size={13}/></button></div></article>
      <article className="metric-card"><div className="metric-top"><span>Due today</span><span className="metric-icon amber"><Clock3 size={16}/></span></div><div className="metric-value">{dueTodayCount.toString().padStart(2, "0")} <small>tasks</small></div><div className="metric-bottom"><span className="muted-emphasis">From assigned tasks</span><button className="metric-link" onClick={() => onOpenScreen("My day")}>View day <ArrowRight size={13}/></button></div></article>
      <article className="metric-card"><div className="metric-top"><span>Waiting for review</span><span className="metric-icon blue-bg"><ShieldCheck size={16}/></span></div><div className="metric-value">{reviewCount.toString().padStart(2, "0")} <small>tasks</small></div><div className="metric-bottom"><span className="status-indicator"><i/> Ready for review</span><button className="metric-link" onClick={() => onOpenScreen("Reviews")}>View reviews <ArrowRight size={13}/></button></div></article>
      <article className="metric-card"><div className="metric-top"><span>Completed</span><span className="metric-icon green-bg"><Check size={16}/></span></div><div className="metric-value">{completedCount.toString().padStart(2, "0")} <small>tasks</small></div><div className="metric-bottom"><span>{completedPercent}% of current tasks</span><span className="tiny-bars"><i/><i/><i/><i/><i/><i/><i/></span></div></article>
    </div>
    <div className="dashboard-grid">
      <section className="panel tasks-panel"><div className="panel-heading"><div><h2>Today’s focus</h2><p>Your work, in one place</p></div><button className="text-button" onClick={() => onOpenScreen("My work")}>View all <ArrowRight size={14}/></button></div><div className="task-tabs"><button className="tab-active">Tasks <span>{tasks.length}</span></button><button onClick={() => onOpenScreen("My day")}>Due today <span>{dueTodayCount}</span></button><button className="filter-button" onClick={() => onOpenScreen("My work")}><Settings2 size={15}/> Filter</button></div><div className="task-list">{tasks.slice(0, 5).map((task) => <div className={`task-row ${task.state === "Completed" ? "task-completed" : ""}`} key={task.id}><button className={`task-check ${task.state === "Completed" ? "checked" : ""}`} aria-label="Mark task complete" onClick={() => onChangeStatus(task, task.state === "Completed" ? "To do" : "Completed")}>{task.state === "Completed" && <Check size={12}/>}</button><div className="task-main"><b>{task.title}</b><div className="task-meta"><span>{task.id.slice(-8).toUpperCase()}</span><i/> <span>{task.project}</span></div></div><span className={`priority priority-${task.priority.toLowerCase()}`}><i/>{task.priority}</span><span className="task-state">{task.state}</span><span className="task-date"><CalendarDays size={13}/>{task.date}</span><span className={`avatar avatar-${task.color}`}>{task.initials}</span></div>)}{tasks.length === 0 && <div className="empty-state dashboard-empty"><ListTodo size={20}/><b>No tasks yet</b><span>Create the first task to get work moving.</span></div>}</div><button className="add-task" onClick={onCreateTask}><Plus size={15}/> Add a task</button></section>
      <section className="panel progress-panel"><div className="panel-heading"><div><h2>Task progress</h2><p>Current organization task status</p></div><button className="more-button" aria-label="Open tasks" onClick={() => onOpenScreen("My work")}><ArrowRight size={15}/></button></div><div className="progress-summary"><div><strong>{completedCount}</strong><span>of {tasks.length} tasks completed</span></div><span className="progress-percent">{completedPercent}%</span></div><div className="progress-track"><i style={{ width: `${completedPercent}%` }}/></div><div className="status-breakdown">{["In progress", "Blocked", "In review", "To do"].map((status) => <button key={status} onClick={() => onOpenScreen("My work")}><span><i className={`priority-dot priority-${status === "Blocked" ? "urgent" : status === "In review" ? "high" : "medium"}`}/>{status}</span><b>{tasks.filter((task) => task.state === status).length}</b></button>)}</div></section>
    </div>
    <div className="lower-grid"><section className="panel projects-panel"><div className="panel-heading"><div><h2>Projects</h2><p>Progress calculated from current tasks</p></div><button className="text-button" onClick={() => onOpenScreen("Projects")}>All projects <ArrowRight size={14}/></button></div><div className="project-cards">{projects.slice(0, 2).map((project, index) => <article className="project-card" key={project.id ?? project.name}><div className="project-card-top"><span className="project-title"><i className={`project-dot ${index === 0 ? "purple" : "orange"}`}/>{project.name}</span><span className="project-state on-track"><i/>{project.status}</span></div><p>Project delivery and tasks</p><div className="project-progress"><div><i style={{ width: `${project.progress}%`, background: index === 0 ? "#8272d8" : "#e5a557" }}/></div><span>{project.progress}%</span></div><div className="project-card-bottom"><span><Users size={14}/> {teamCount} members</span><span><CalendarDays size={13}/> {project.due}</span></div></article>)}{projects.length === 0 && <div className="empty-state dashboard-empty"><FolderKanban size={20}/><b>No projects yet</b><span>Create a project to group work.</span></div>}</div></section><section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent work updates</h2><p>Updates submitted in this session</p></div><button className="more-button" aria-label="Open work updates" onClick={() => onOpenScreen("Work updates")}><ArrowRight size={15}/></button></div><div className="activity-list">{workUpdates.slice(0, 3).map((update, index) => <div className="activity-item" key={`${update.taskId}-${index}`}><span className="activity-avatar avatar-user">{userName.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><div><p><b>{update.task}</b></p><span>{update.progress}% complete · {update.when}</span></div></div>)}{workUpdates.length === 0 && <div className="empty-state dashboard-empty"><Activity size={20}/><b>No recent work updates</b><span>Submitted updates will appear here.</span></div>}</div></section></div>
  </>;
}
