"use client";

import { useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import type { WorkspaceScreenProps } from "./types";

// REPORTS SCREEN: shows stored task counts, overdue work, and recorded time from the API.
// It avoids estimated scores so a manager can trust the figures shown to the team.
export function ReportsScreen({ organizationId, workspaceId }: WorkspaceScreenProps) {
  const [report, setReport] = useState<{ total: number; counts: Record<string, number>; overdue: number; trackedMinutes: number; completedThisWeek?: number; blocked?: number; awaitingReview?: number; upcoming?: number }>();
  useEffect(() => { void apiFetch<typeof report>(`/organizations/${organizationId}/reports/summary?workspaceId=${encodeURIComponent(workspaceId ?? "")}`).then(setReport).catch(() => setReport(undefined)); }, [organizationId, workspaceId]);
  const download = () => { if (!report) return; const lines = [["Metric", "Value"], ["Total tasks", report.total], ["Overdue", report.overdue], ["Blocked", report.blocked ?? 0], ["Awaiting review", report.awaitingReview ?? 0], ["Upcoming", report.upcoming ?? 0], ["Completed this week", report.completedThisWeek ?? 0], ["Tracked minutes", report.trackedMinutes], ...Object.entries(report.counts).map(([status, count]) => [status, count])]; const blob = new Blob([lines.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "flownexa-workspace-report.csv"; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="form-card"><h2>Workspace report</h2><p>Current task status and recorded time, calculated from saved workspace data.</p>{report ? <><button className="secondary-button" onClick={download}>Export CSV</button><div className="metric-grid"><article className="metric-card"><span>Total tasks</span><h2>{report.total}</h2></article><article className="metric-card"><span>Overdue</span><h2>{report.overdue}</h2></article><article className="metric-card"><span>Blocked</span><h2>{report.blocked ?? 0}</h2></article><article className="metric-card"><span>Awaiting review</span><h2>{report.awaitingReview ?? 0}</h2></article><article className="metric-card"><span>Upcoming</span><h2>{report.upcoming ?? 0}</h2></article><article className="metric-card"><span>Completed this week</span><h2>{report.completedThisWeek ?? 0}</h2></article><article className="metric-card"><span>Tracked time</span><h2>{Math.floor(report.trackedMinutes / 60)}h {report.trackedMinutes % 60}m</h2></article></div>{Object.entries(report.counts).map(([status, count]) => <div className="day-task" key={status}><b>{status.replaceAll("_", " ")}</b><span>{count}</span></div>)}</> : <p>Report data is not available.</p>}</div>;
}
